### ISSUE TITLE
Error in xy.coords(x, y, xlabel, ylabel, log) and Error in read.table("counts.txt", header = F, row.names = 1)

### ISSUE THREAD

**Issue by HelloYiHan** [alanzos/ExInAtor#1]
Hi, i am very interested in ExInAtor but have a little problem about it.
I uncompressed the ExInAtor-master.zip and there were All_files_v0.zip and All_files_v1.zip. Then i unompressed both of them.
1.For  All_files_v0, I copied reference genome hg19.fa to Inputs directory and ran:
$ python2.7 Main.py -i Inputs/Breast.bed -o outputs_default -f Inputs/hg19.fa -g Inputs/gencode.v19.long_noncoding_RNAs.gtf -s Inputs/chromosomes.txt -k Inputs/3mers.txt -w Inputs/gencode.v19.annotation.gtf -c 6 -n 119 -b 10000
I got :
Arguments correctly inserted: 0 seconds 
Starting the analysis of Inputs/Breast: 0 seconds 
	Genes gathered: 0 seconds 
	Kmers gathered: 0 seconds 
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ
Calls: plot -> plot.default -> xy.coords
Execution halted
	Qvalues calculated: 1 seconds 
2.For All_files_v1, I copied reference genome hg19.fa to Inputs directory and ran:
$ python2.7 Main.py -i Inputs/Breast.bed -o outputs_default -f Inputs/hg19.fa -g Inputs/gencode.v19.long_noncoding_RNAs.gtf -s Inputs/chromosomes.txt -k Inputs/3mers.txt -w Inputs/gencode.v19.annotation.gtf -c 6 -n 119 -b 10000
I got:
Arguments correctly inserted: 0 seconds 
Starting the analysis of Inputs/Breast: 0 seconds 
	Genes gathered: 0 seconds 
Error in read.table("counts.txt", header = F, row.names = 1) : 
  no lines available in input
Execution halted
	Qvalues calculated: 0 seconds 
I was wandering what was wrong and how to run ExInAtor correctly.
Thanks

**Comment by alanzos** [comment]
Hello YiHan,

Thanks for your interest in ExInAtor.

Please check these two points:

- Use the full path to each file, for example: `~/Downloads/All_files/Inputs/Breast.bed`

- Check that you have the same versions for the required software (mainly bedtools and python): https://github.com/alanzos/ExInAtor#requirements

I was able to correctly run ExInAtor with the following command after downloading "All_files_v1":
`python2.7 Main.py -i ~/Downloads/All_files/Inputs/Breast.bed -o ~/Downloads/All_files/Outputs2 -f ~/Downloads/All_files/Inputs/Genome_v19.fasta -g ~/Downloads/All_files/Inputs/gencode.v19.long_noncoding_RNAs.gtf -s ~/Downloads/All_files/Inputs/chromosomes.txt -k ~/Downloads/All_files/Inputs/3mers.txt -w ~/Downloads/All_files/Inputs/gencode.v19.annotation.gtf -c 6 -n 119 -b 10000`

Please let me know if still does not work after you check the previous two points.

Cheers,
Andrés.

**Comment by HelloYiHan** [comment]
Hi, Andrés,
Thank you for all your assistance.
I checked the version of the software meets the requirement.
Linux version 2.6.32-358.el6.x86_64
bedtools v2.24.0
Python 2.7.14
R version 3.4.1
Awk 3.1.7
Then I used the full path to each file but it still had some problem as below:
***** ERROR: -nms option is deprecated. Please see the documentation for the -c and -o column operation options. *****
Tool:    bedtools merge (aka mergeBed)
Version: v2.24.0
Summary: Merges overlapping BED/GFF/VCF entries into a single interval.

Usage:   bedtools merge [OPTIONS] -i <bed/gff/vcf>

Options: 

        -s      Force strandedness.  That is, only merge features
                 that are on the same strand.
                - By default, merging is done without respect to strand.

        -S      Force merge for one specific strand only.
                Follow with + or - to force merge from only
                the forward or reverse strand, respectively.
                - By default, merging is done without respect to strand.

        -d      Maximum distance between features allowed for features
                to be merged.
                - Def. 0. That is, overlapping & book-ended features are merged.
                - (INTEGER)
                - Note: negative values enforce the number of b.p. required for overlap.

        -c      Specify columns from the B file to map onto intervals in A.
                Default: 5.
                Multiple columns can be specified in a comma-delimited list.

        -o      Specify the operation that should be applied to -c.
                Valid operations:
                    sum, min, max, absmin, absmax,
                    mean, median,
                    collapse (i.e., print a delimited list (duplicates allowed)), 
                    distinct (i.e., print a delimited list (NO duplicates allowed)), 
                    count
                    count_distinct (i.e., a count of the unique values in the column), 
                    first (i.e., just the first value in the column), 
                    last (i.e., just the last value in the column), 
                Default: sum
                Multiple operations can be specified in a comma-delimited list.

                If there is only column, but multiple operations, all operations will be
                applied on that column. Likewise, if there is only one operation, but
                multiple columns, that operation will be applied to all columns.
                Otherwise, the number of columns must match the the number of operations,
                and will be applied in respective order.
                E.g., "-c 5,4,6 -o sum,mean,count" will give the sum of column 5,
                the mean of column 4, and the count of column 6.
                The order of output columns will match the ordering given in the command.


        -delim  Specify a custom delimiter for the collapse operations.
                - Example: -delim "|"
                - Default: ",".

        -prec   Sets the decimal precision for output (Default: 5)

        -bed    If using BAM input, write output as BED.

        -header Print the header from the A file prior to results.

        -nobuf  Disable buffered output. Using this option will cause each line
                of output to be printed as it is generated, rather than saved
                in a buffer. This will make printing large output files 
                noticeably slower, but can be useful in conjunction with
                other software tools and scripts that need to process one
                line of bedtools output at a time.

        -iobuf  Specify amount of memory to use for input buffer.
                Takes an integer argument. Optional suffixes K/M/G supported.
                Note: currently has no effect with compressed files.

Notes: 
        (1) The input file (-i) file must be sorted by chrom, then start.
WARNING. chromosome (1) was not found in the FASTA file. Skipping.
.....so many warnings from 1 to Y
WARNING. chromosome (Y) was not found in the FASTA file. Skipping.
Arguments correctly inserted: 0 seconds 
Starting the analysis of /data/itmll/yhan/exinator/ExInAtor-master/All_files/Inputs/Breast: 0 seconds 
        BED files created for merged exons and introns: 6 seconds 
        Mutations counted in merged exons mutations and introns: 28 seconds 
        Genes gathered: 28 seconds 
        Kmers gathered: 28 seconds 
        Kmers counted: 30 seconds 
        All information combined: 32 seconds 
        Table_kamer_count.txt parsed: 36 seconds 
Error in read.table("counts.txt", header = F, row.names = 1) : 
  no lines available in input
Execution halted
        Counts calculated: 36 seconds 
        Qvalues calculated: 36 seconds 

I would appreciate it if you could help me solve this problem.
Thank you again.
Sincerely,
Yi Han

**Comment by alanzos** [comment]
Ok, I see the problem, you are using bedtools v2.24.0 and ExInAtor works with v2.19.1, and the "merge" changed a little bit between those two versions.
Please install version 2.19 and try again. I will edit the documentation to make it more clear and later on, I will also change ExInAtor so it can work with newer versions of bedtools.
Let me know if you have more problems.

**Comment by HelloYiHan** [comment]
Hi Andrés,

Thank you for all your kind assistance.

I install the v2.19.1 version of bedtools and the error of bedtools disappears. But it still does not work. The result is as below

WARNING. chromosome (1) was not found in the FASTA file. Skipping.
(so many WARNING)
WARNING. chromosome (Y) was not found in the FASTA file. Skipping.
Arguments correctly inserted: 0 seconds 
Starting the analysis of /home/yihan/Downloads/ExInAtor-master/All_files/Inputs/Breast: 0 seconds 
        BED files created for merged exons and introns: 11 seconds 
        Mutations counted in merged exons mutations and introns: 12 seconds 
        Genes gathered: 12 seconds 
        Kmers gathered: 12 seconds 
        Kmers counted: 13 seconds 
        All information combined: 14 seconds 
        Table_kamer_count.txt parsed: 16 seconds 
Error in read.table("counts.txt", header = F, row.names = 1) : 
  no lines available in input
Execution halted
        Counts calculated: 16 seconds 
        Qvalues calculated: 16 seconds 

I was wandering if the R script works well.  I found the counts.txt was blank.
ls -lh output_test/ 
-rw-rw-r-- 1 yihan yihan    0 Aug 17 11:40 counts.txt
-rw-rw-r-- 1 yihan yihan    0 Aug 17 11:40 exonic_kmers.txt
-rw-rw-r-- 1 yihan yihan 567K Aug 17 11:40 genes.bed
-rw-rw-r-- 1 yihan yihan    0 Aug 17 11:40 intronic_kmers.txt
-rw-rw-r-- 1 yihan yihan  26M Aug 17 11:40 table_kmer_counts.txt

Thanks again for your help.

**Comment by alanzos** [comment]
Hello,
The problem is with the chromosome headers in the FASTA file. I will correct the script, in the meantime please download, uncompress and use this FASTA file:
https://www.dropbox.com/s/a6vthezotm6iaih/Genome_v19.fasta.gz?dl=0
Let me know if any other problem appears.

**Comment by HelloYiHan** [comment]
Hi Andrés,
Great! It finally works! I am really happy and thank you for all your kind help.
I have another question and request your guidance.
ExInAtor can be used on protein-coding genes and what should I do if I want to apply ExInAtor on protein-coding genes of my own mutation data?  Do I need to change the gencode.v19.long_noncoding_RNAs.gtf and gencode.v19.annotation.gtf ?

Best,
Yi Han

**Comment by alanzos** [comment]
For protein coding genes you have two options:

a) Run all gencode genes, therefore you replace gencode.v19.long_noncoding_RNAs.gtf by gencode.v19.annotation.gtf. Then you will have to see which of the candidates are protein coding.

b) Run only coding genes from gencode, this way you need to create a new GTF file having only protein coding genes (with their exons). In this Dropbox link you can find such file:
https://www.dropbox.com/s/f36rgshicb51e06/gencode.v19.protein_coding_filtered_noM.gtf?dl=0
